openapi: 3.0.0
info:
  version: 1.0.0
  title: IBM-SL
servers:
  - url: https://ibm-sl-api.deno.dev/
    description: Production server
  - url: http://localhost:8000
    description: Local server
components:
  schemas: {}
  parameters: {}
paths:
  /api/estimate:
    post:
      description: >-
        Accepts a `route` as an input. A `route` consists of one or multiple
        `stages`.The returned value is an object containing a `total_kg` that
        represents the total estimated emission for the given `route` and a list
        numbers representing the estimated emissions for each `stage`.
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                properties:
                  id:
                    type: string
                  stages:
                    type: array
                    items:
                      allOf:
                        - anyOf:
                            - type: object
                              properties:
                                transport_form:
                                  type: string
                                  enum:
                                    - truck
                                    - etruck
                                    - train
                                    - aircraft
                                    - cargoship
                                  description: >-
                                    The vehicle type that is used in this
                                    `stage`.
                                distance_km:
                                  type: number
                                  description: >-
                                    The distance of this `stage` of the route in
                                    kilometers.
                              required:
                                - transport_form
                                - distance_km
                            - type: object
                              properties:
                                transport_form:
                                  type: string
                                  enum:
                                    - truck
                                    - etruck
                                  description: >-
                                    The vehicle type that is used in this
                                    `stage`.
                                from:
                                  type: object
                                  properties:
                                    city:
                                      type: string
                                      description: The city query.
                                      example: New York
                                    country:
                                      type: string
                                      description: >-
                                        The country query that the city should
                                        be in. (Optional)
                                      example: United States
                                  required:
                                    - city
                                  description: >-
                                    The address of the starting point of this
                                    `stage`.
                                  examples:
                                    - city: New
                                    - city: Copen
                                      country: Denmark
                                to:
                                  type: object
                                  properties:
                                    city:
                                      type: string
                                      description: The city query.
                                      example: New York
                                    country:
                                      type: string
                                      description: >-
                                        The country query that the city should
                                        be in. (Optional)
                                      example: United States
                                  required:
                                    - city
                                  description: >-
                                    The address of the destination of this
                                    `stage`.
                                  examples:
                                    - city: New
                                    - city: Copen
                                      country: Denmark
                              required:
                                - transport_form
                                - from
                                - to
                        - type: object
                          properties:
                            cargo_t:
                              type: number
                              description: The weight of the cargo of this `stage` in tons.
                      description: >-
                        A `stage` that contains a `transport_form` and either a
                        `distance_km` or `from` and `to`.
                      example:
                        transport_form: truck
                        distance_km: 100
                    description: >-
                      List of objects that each represents a `stage` of the
                      `route`.
                    example:
                      - transport_form: truck
                        distance_km: 100
                      - transport_form: truck
                        from:
                          city: New York
                          country: United States
                        to:
                          city: Los Angeles
                      - transport_form: etruck
                        cargo_t: 10
                        distance_km: 100
                      - transport_form: train
                        cargo_t: 50
                        distance_km: 500
                      - transport_form: aircraft
                        cargo_t: 2
                        distance_km: 300
                      - transport_form: cargoship
                        distance_km: 300
                required:
                  - id
                  - stages
              description: Set of objects that each represents a `route` of a `chain`.
              example:
                - id: Primary Route
                  stages:
                    - transport_form: truck
                      cargo_t: 10
                      distance_km: 225
                    - transport_form: truck
                      from:
                        city: Copenhagen
                      to:
                        city: Hamburg
                        country: Germany
      responses:
        '200':
          description: The estimated emission for each `stage` as well as the total.
          content:
            application/json:
              schema:
                type: object
                properties:
                  chain_kg:
                    type: number
                    description: >-
                      The estimated emission for the whole `chain` in kilograms,
                      i.e. the sum of each `route` (before rounding).
                    example: 217
                  routes:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          description: A identifier that uniquely identifies a `route`.
                          example: Route 1
                        route_kg:
                          type: number
                          description: The estimated emission for the `route` in kilograms.
                        stages:
                          type: array
                          items:
                            type: object
                            properties:
                              stage_kg:
                                type: number
                                description: The estimated emissions for this `stage`.
                              transport_form:
                                type: string
                                enum:
                                  - truck
                                  - etruck
                                  - train
                                  - aircraft
                                  - cargoship
                                description: The vehicle type that is used in this `stage`.
                            required:
                              - stage_kg
                              - transport_form
                      required:
                        - id
                        - route_kg
                        - stages
                required:
                  - chain_kg
                  - routes
                description: >-
                  The estimations for this chain as well as the total. All the
                  estimations are rounded to nearest integer, though, to not
                  lose too much precision, the sums have been calculated before
                  rounding.
                example:
                  chain_kg: 7057
                  routes:
                    - id: Primary Route
                      route_kg: 6713
                      stages:
                        - stage_kg: 105
                          transport_form: truck
                        - stage_kg: 4713
                          transport_form: truck
                        - stage_kg: 70
                          transport_form: etruck
                        - stage_kg: 325
                          transport_form: train
                        - stage_kg: 1500
                          transport_form: aircraft
                    - id: Secondary Route
                      route_kg: 344
                      stages:
                        - stage_kg: 134
                          transport_form: etruck
                        - stage_kg: 210
                          transport_form: train
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                anyOf:
                  - type: object
                    properties:
                      error:
                        type: string
                        enum:
                          - Could not connect locations
                      route_id:
                        type: string
                        description: A identifier that uniquely identifies a `route`.
                        example: Route 1
                      stage_index:
                        type: number
                      from:
                        type: object
                        properties:
                          city:
                            type: string
                            description: The city query.
                            example: New York
                          country:
                            type: string
                            description: >-
                              The country query that the city should be in.
                              (Optional)
                            example: United States
                        required:
                          - city
                        description: An address containing a city and optionally a country.
                        examples:
                          - city: New
                          - city: Copen
                            country: Denmark
                      to:
                        type: object
                        properties:
                          city:
                            type: string
                            description: The city query.
                            example: New York
                          country:
                            type: string
                            description: >-
                              The country query that the city should be in.
                              (Optional)
                            example: United States
                        required:
                          - city
                        description: An address containing a city and optionally a country.
                        examples:
                          - city: New
                          - city: Copen
                            country: Denmark
                    required:
                      - error
                      - route_id
                      - stage_index
                      - from
                      - to
                  - type: object
                    properties:
                      error:
                        type: string
                        enum:
                          - No such address
                      fromOrTo:
                        type: string
                        enum:
                          - from
                          - to
                        description: Specifies if an address is an origin or destination.
                    required:
                      - error
                      - fromOrTo
                  - type: object
                    properties:
                      error:
                        type: string
                        enum:
                          - Ambiguous address
                      fromOrTo:
                        type: string
                        enum:
                          - from
                          - to
                        description: Specifies if an address is an origin or destination.
                      addresses:
                        type: array
                        items:
                          type: object
                          properties:
                            city:
                              type: string
                              description: The city query.
                              example: New York
                            country:
                              type: string
                              description: >-
                                The country query that the city should be in.
                                (Optional)
                              example: United States
                          required:
                            - city
                          description: >-
                            An address containing a city and optionally a
                            country.
                          examples:
                            - city: New
                            - city: Copen
                              country: Denmark
                    required:
                      - error
                      - fromOrTo
                      - addresses
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Error fetching data
                required:
                  - error
                description: An error response.
                example:
                  error: No results found
  /api/suggest:
    post:
      description: >-
        Accepts an address object which consists of a `city` and a `country`
        field. The two fields can be incomplete or empty. The response is a list
        of suggestions for the `city` and `country` fields, where the
        suggestions strictly matches the start of the input fields.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                city:
                  type: string
                  description: The city query.
                  example: New York
                country:
                  type: string
                  description: The country query that the city should be in. (Optional)
                  example: United States
              required:
                - city
              description: An address containing a city and optionally a country.
              examples:
                - city: New
                - city: Copen
                  country: Denmark
      responses:
        '200':
          application/json:
            schema:
              _def:
                type:
                  _def:
                    unknownKeys: strip
                    catchall:
                      _def:
                        typeName: ZodNever
                    typeName: ZodObject
                  _cached: null
                minLength: null
                maxLength: null
                exactLength: null
                typeName: ZodArray
                openapi:
                  metadata:
                    description: A list of city suggestions and their countries
          description: A list of suggestions for the `city` and `country` fields.
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Error fetching data
                required:
                  - error
                description: An error response.
                example:
                  error: No results found
  /api/fuzzy:
    post:
      description: >-
        Accepts an address object which consists of a `city` and a `country`
        field. The two fields can be incomplete or empty. The response is a list
        of suggestions for the `city` and `country` fields, where the
        suggestions loosely matches the input fields.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                city:
                  type: string
                  description: The city query.
                  example: New York
                country:
                  type: string
                  description: The country query that the city should be in. (Optional)
                  example: United States
              required:
                - city
              description: An address containing a city and optionally a country.
              examples:
                - city: New
                - city: Copen
                  country: Denmark
      responses:
        '200':
          application/json:
            schema:
              _def:
                type:
                  _def:
                    unknownKeys: strip
                    catchall:
                      _def:
                        typeName: ZodNever
                    typeName: ZodObject
                  _cached: null
                minLength: null
                maxLength: null
                exactLength: null
                typeName: ZodArray
                openapi:
                  metadata:
                    description: A list of city suggestions and their countries
          description: A list of suggestions for the `city` and `country` fields.
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Error fetching data
                required:
                  - error
                description: An error response.
                example:
                  error: No results found
